---
abstract: 'perldoc that also checks perldoc.jp'
author:
  - 'Kenichi Ishigaki <ishigaki@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.132620'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-PerldocJp
no_index:
  directory:
    - t
    - inc
requires:
  Encode: 0
  LWP: 0
  Path::Extended: 0.12
  Pod::Perldoc: 3.15
  Pod::Simple: 3.08
  Pod::Text: 3.13
  Term::Encoding: 0
  Test::More: 0.47
  Test::UseAllModules: 0.10
  URI::Escape: 0
version: 0.15
